### ISSUE TITLE
Shape in WebGL is just black

### ISSUE THREAD

**Issue by Hendiadyoin1** [processing/p5.js#2718]
I've tried to convert a script I've made like tutorialmade by the CodingTrain and the terrain just turned out black, althought i ma using noFill()
can somebody help me?

Code:
`let scl;
let s;
let fly = 0;
let speed = -1;
function setup(){
  createCanvas(400,400,WEBGL);
  scl=0.01;
  s = createSlider(-2,2,-1,0.1);
}
function draw(){
  speed = s.value();
	noFill();
  background(200);
  translate(-600,width/3,-1300);
  rotateX(-3*PI/8);
  strokeWeight(0.1);
  stroke(0,0,0,10);
  for(let y = 0;y<1000;y+=20){
    beginShape(TRIANGLE_STRIP);
    noFill();
    for(let x=0;x<1300;x+=20){
      vertex(x,y,noise(x*scl,(y+fly)*scl)*100);
      vertex(x,y+20,noise(x*scl,(y+20+fly)*scl)*100);
    }
    endShape();
  }
  fly += speed;
  //pf.html(floor(frameRate));
}
`

**Comment by kjhollen** [comment]
Hi @Hendiadyoin1 can you describe the expected outcome in a little more detail and tell us which version of p5.js you're using?

I wasn't able to run the code as posted, but removing the commented part at the end produced something—however, I'm not sure what your intent with the code is. Can you reduce it to a simpler example that produces the issue?

**Comment by Hendiadyoin1** [comment]
well i think i am running the latest version (v0.5.4) and i'm using the index .html to run it
index:
`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Clock</title>
    <script src="libraries/p5.js" type="text/javascript"></script>

    <script src="libraries/p5.dom.js" type="text/javascript"></script>
    <script src="libraries/p5.sound.js" type="text/javascript"></script>

    <script src="sketch.js" type="text/javascript"></script>

    <style> body {padding: 0; margin: 0;} canvas {vertical-align: top;} </style>
  </head>
  <body>
  </body>
</html>
`
this is how it looks like:
![plane](https://user-images.githubusercontent.com/37629766/37862416-c45d8bf6-2f4c-11e8-9e9e-fb95e55f2aaf.PNG)

and this how it should look like:
![plane2](https://user-images.githubusercontent.com/37629766/37862430-062161d4-2f4d-11e8-8780-527677794fa4.PNG)

**Comment by Spongman** [comment]
The latest version of p5 is actually 0.6.0. You might have better results with that.

**Comment by Spongman** [comment]
Also, if you intend to fill & light this then please see issue #2609 for a discussion on related issues and possible workarounds.

**Comment by Hendiadyoin1** [comment]
well thank you but with the noFill() option lighting shouldn't cause this problem, should it?

**Comment by Spongman** [comment]
no, the triangle strip method will work fine if you're just drawing lines.

**Comment by kjhollen** [comment]
the code is working with the latest version is 0.6.0. 

at first I was seeing a bunch of dots moving around instead of triangles/lines, but it seems that's because the strokeWeight is set to 0.1, which means it will be round down to 0 most of the time. I set the strokeWeight to 1 and things look as expected.

**Comment by Spongman** [comment]
ha! you beat me to it by about 30 seconds ;-)

... additionally `setAttributes('antialias', true)` will help a little.

**Comment by Hendiadyoin1** [comment]
Thank you all and setAtributes(..) give sme this error:

"
Uncaught TypeError: this._renderer._resetContext is not a function
    at p5.setAttributes (p5.js:72083)
    at setup (sketch.js:7)
    at p5.<anonymous> (p5.js:46215)
    at p5.<anonymous> (p5.js:46150)
    at new p5 (p5.js:46434)
    at _globalInit (p5.js:48404)
"

**Comment by Spongman** [comment]
oh, soryr. it's best to put that call immediately after the call to `createCanvas()`

**Comment by Hendiadyoin1** [comment]
well thx...
question is it easy to change it to GPU-processing to increase fps?

**Comment by Spongman** [comment]
if you're calling `createCanvas(..., ..., WEBGL)` in your `setup` function, then you _are_ using the GPU.

**Comment by Hendiadyoin1** [comment]
Ok with out it the antialias wouldnt work i think but thx
