### ISSUE TITLE
p5.SoundRecorder demo not working with versions after 0.9.0

### ISSUE THREAD

**Issue by samheckle** [processing/p5.js#6902]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [X] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build process
- [ ] Unit testing
- [ ] Internationalization
- [ ] Friendly errors
- [X] Other (specify if possible)

### p5.js version

1.9.1

### Web browser and version

Firefox 124.0

### Operating system

MacOSX

### Steps:
1. Copy example code from [p5.SoundRecorder reference](https://p5js.org/reference/#/p5.SoundRecorder)
2. Paste into new sketch [here is mine](https://editor.p5js.org/samheckle/sketches/NxjC3VwAE)
3. Run the sketch
4. Click the canvas to record sound
5. Record a snippet
6. Stop recording by clicking canvas
7. Errors in console: `TypeError: arraySequence[channel] is undefined` and `Uncaught DOMException: BaseAudioContext.createBuffer: Length (0) is out of range`
8. Try to download file by clicking canvas
9. Errors in console: `undefined: undefined`

### Other Notes
* I was able to fix it by switching my p5 version to `0.9.0`, but why doesn't it work with the any versions after `0.9.0`?
* It is has the same problem in Chrome
